/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;
import Back.*;
import javax.swing.JOptionPane;
import BD.BD;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author alanm
 */

public class VentanaTrabajadores extends javax.swing.JFrame {
    Trabajador trbj=null;
VentanaDueño Vd=null;
ImageIcon icon = new ImageIcon("src\\IconosProyecto\\Trabajaadores.jpg");
BD BD = null;
DefaultTableModel modelotrbj = new DefaultTableModel();
    /**
     * Creates new form VentanaTrabajadores
     */
    public VentanaTrabajadores() {
        initComponents();
    }
     public VentanaTrabajadores(VentanaDueño Vd,Trabajador trbj) {
         this.Vd=Vd;
         this.trbj=trbj;
         BD=new BD();
          modelotrbj=BD.crear_modelo_trabajador(modelotrbj);
    
        initComponents();
    }
     
     public void limpiar(){
         txtNombre.setText("");
          txtEdad.setText("");
           txtEmail.setText("");
            txtPago.setText("");
            txtHoras.setText("");
            txtMatricula.setText("");
         txtNombre1.setText("");
          txtEdad1.setText("");
           txtEmail1.setText("");
            txtPago1.setText("");
            txtPuesto1.setText("");
            txtHoras1.setText("");
            txtBuscar.setText("");
     }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupPuesto = new javax.swing.ButtonGroup();
        jSpinner1 = new javax.swing.JSpinner();
        tabTrabajdores = new javax.swing.JTabbedPane();
        tabIngresarT = new javax.swing.JPanel();
        jblNombre = new javax.swing.JLabel();
        txtPago = new javax.swing.JTextField();
        jblEdad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jblPuesto = new javax.swing.JLabel();
        rbtnVendedor = new javax.swing.JRadioButton();
        rbtnAlmacen = new javax.swing.JRadioButton();
        rbtnLimpieza = new javax.swing.JRadioButton();
        rbtnDiseñador = new javax.swing.JRadioButton();
        rbtnProductor = new javax.swing.JRadioButton();
        jblPago = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jblHoras = new javax.swing.JLabel();
        txtHoras = new javax.swing.JTextField();
        jblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        rbtnOtro = new javax.swing.JRadioButton();
        btnGuardarN = new javax.swing.JLabel();
        tabTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblT = new javax.swing.JTable();
        txtBuscarTabla = new javax.swing.JTextField();
        lblBucarTabla = new javax.swing.JLabel();
        btnBuscarN = new javax.swing.JLabel();
        tabEditarTrabajador = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        jblEdad1 = new javax.swing.JLabel();
        txtEdad1 = new javax.swing.JTextField();
        jblEmail1 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        jblPago1 = new javax.swing.JLabel();
        txtPago1 = new javax.swing.JTextField();
        jblHoras1 = new javax.swing.JLabel();
        txtHoras1 = new javax.swing.JTextField();
        jblPuesto1 = new javax.swing.JLabel();
        txtPuesto1 = new javax.swing.JTextField();
        btnGuadarNE = new javax.swing.JLabel();
        btnEliminarN = new javax.swing.JLabel();
        btnActN = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jblTrabajadores = new javax.swing.JLabel();
        volver = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(99, 82, 62));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabTrabajdores.setBackground(new java.awt.Color(138, 114, 86));
        tabTrabajdores.setForeground(new java.awt.Color(255, 255, 255));

        tabIngresarT.setBackground(new java.awt.Color(99, 82, 62));

        jblNombre.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblNombre.setText("Nombre");

        txtPago.setBackground(new java.awt.Color(138, 114, 86));
        txtPago.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));

        jblEdad.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblEdad.setText("Edad");

        txtNombre.setBackground(new java.awt.Color(138, 114, 86));
        txtNombre.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));

        jblEmail.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblEmail.setText("Email");

        txtEmail.setBackground(new java.awt.Color(138, 114, 86));
        txtEmail.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));

        jblPuesto.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblPuesto.setText("Puesto");

        btngroupPuesto.add(rbtnVendedor);
        rbtnVendedor.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        rbtnVendedor.setSelected(true);
        rbtnVendedor.setText("Vendedor");

        btngroupPuesto.add(rbtnAlmacen);
        rbtnAlmacen.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        rbtnAlmacen.setText("Almacen");
        rbtnAlmacen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));

        btngroupPuesto.add(rbtnLimpieza);
        rbtnLimpieza.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        rbtnLimpieza.setText("Limpieza");

        btngroupPuesto.add(rbtnDiseñador);
        rbtnDiseñador.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        rbtnDiseñador.setText("Diseñador");

        btngroupPuesto.add(rbtnProductor);
        rbtnProductor.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        rbtnProductor.setText("Productor");

        jblPago.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblPago.setText("Pago x Hora");

        txtEdad.setBackground(new java.awt.Color(138, 114, 86));
        txtEdad.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));

        jblHoras.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblHoras.setText("Horas Trabajadas");

        txtHoras.setBackground(new java.awt.Color(138, 114, 86));
        txtHoras.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtHoras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));

        jblMatricula.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblMatricula.setText("Matricula");

        txtMatricula.setBackground(new java.awt.Color(138, 114, 86));
        txtMatricula.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));

        btngroupPuesto.add(rbtnOtro);
        rbtnOtro.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        rbtnOtro.setText("Otro");

        btnGuardarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/save.png"))); // NOI18N
        btnGuardarN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarNMousePressed(evt);
            }
        });
        btnGuardarN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGuardarNKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout tabIngresarTLayout = new javax.swing.GroupLayout(tabIngresarT);
        tabIngresarT.setLayout(tabIngresarTLayout);
        tabIngresarTLayout.setHorizontalGroup(
            tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabIngresarTLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabIngresarTLayout.createSequentialGroup()
                        .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabIngresarTLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jblMatricula))
                            .addGroup(tabIngresarTLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jblPago)))
                        .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabIngresarTLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtPago))
                            .addGroup(tabIngresarTLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(txtMatricula))))
                    .addGroup(tabIngresarTLayout.createSequentialGroup()
                        .addComponent(jblHoras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtHoras))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabIngresarTLayout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jblEdad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jblEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jblPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabIngresarTLayout.createSequentialGroup()
                                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtnDiseñador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbtnVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(tabIngresarTLayout.createSequentialGroup()
                                        .addComponent(rbtnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(tabIngresarTLayout.createSequentialGroup()
                                        .addComponent(rbtnProductor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbtnOtro, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEdad)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabIngresarTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarN)
                .addContainerGap())
        );
        tabIngresarTLayout.setVerticalGroup(
            tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabIngresarTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblPuesto)
                    .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnVendedor)
                        .addComponent(rbtnAlmacen)
                        .addComponent(rbtnLimpieza)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnDiseñador)
                    .addComponent(rbtnProductor)
                    .addComponent(rbtnOtro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabIngresarTLayout.createSequentialGroup()
                        .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblPago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabIngresarTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jblHoras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jblMatricula, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(47, 47, 47)
                .addComponent(btnGuardarN)
                .addGap(16, 16, 16))
        );

        tabTrabajdores.addTab("Ingresar⠀⠀⠀⠀", tabIngresarT);

        tabTabla.setBackground(new java.awt.Color(99, 82, 62));
        tabTabla.setForeground(new java.awt.Color(99, 82, 62));

        jScrollPane1.setBackground(new java.awt.Color(99, 82, 62));
        jScrollPane1.setForeground(new java.awt.Color(99, 82, 62));

        tblT.setBackground(new java.awt.Color(138, 114, 86));
        tblT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));
        tblT.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        tblT.setForeground(new java.awt.Color(99, 82, 62));
        tblT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblT.setGridColor(new java.awt.Color(99, 82, 62));
        tblT.setSelectionBackground(new java.awt.Color(99, 82, 62));
        tblT.setSelectionForeground(new java.awt.Color(99, 82, 62));
        jScrollPane1.setViewportView(tblT);

        txtBuscarTabla.setBackground(new java.awt.Color(138, 114, 86));
        txtBuscarTabla.setColumns(2);
        txtBuscarTabla.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtBuscarTabla.setToolTipText("ola");
        txtBuscarTabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));
        txtBuscarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarTablaActionPerformed(evt);
            }
        });

        lblBucarTabla.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblBucarTabla.setText("Ingrese Matricula de un trabajador");

        btnBuscarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/buscar.png"))); // NOI18N
        btnBuscarN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarNMousePressed(evt);
            }
        });

        javax.swing.GroupLayout tabTablaLayout = new javax.swing.GroupLayout(tabTabla);
        tabTabla.setLayout(tabTablaLayout);
        tabTablaLayout.setHorizontalGroup(
            tabTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addGroup(tabTablaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBucarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabTablaLayout.setVerticalGroup(
            tabTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(tabTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBucarTabla))
                    .addComponent(btnBuscarN))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        tabTrabajdores.addTab("Ver ⠀⠀⠀", tabTabla);

        tabEditarTrabajador.setBackground(new java.awt.Color(99, 82, 62));
        tabEditarTrabajador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscar.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblBuscar.setText("Buscar Trabajador por Matricula");
        tabEditarTrabajador.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 24, 229, -1));

        txtBuscar.setBackground(new java.awt.Color(99, 82, 62));
        txtBuscar.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtBuscar.setBorder(null);
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        tabEditarTrabajador.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 200, 20));

        jblNombre1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblNombre1.setText("Nombre");
        tabEditarTrabajador.add(jblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 65, 61, -1));

        txtNombre1.setBackground(new java.awt.Color(138, 114, 86));
        txtNombre1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtNombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));
        txtNombre1.setEnabled(false);
        tabEditarTrabajador.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 65, 395, -1));

        jblEdad1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblEdad1.setText("Edad");
        tabEditarTrabajador.add(jblEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 95, 61, -1));

        txtEdad1.setBackground(new java.awt.Color(138, 114, 86));
        txtEdad1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtEdad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));
        txtEdad1.setEnabled(false);
        tabEditarTrabajador.add(txtEdad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 93, 395, -1));

        jblEmail1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblEmail1.setText("Email");
        tabEditarTrabajador.add(jblEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 123, 61, -1));

        txtEmail1.setBackground(new java.awt.Color(138, 114, 86));
        txtEmail1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtEmail1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));
        txtEmail1.setEnabled(false);
        tabEditarTrabajador.add(txtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 121, 395, -1));

        jblPago1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblPago1.setText("Pago x Hora");
        tabEditarTrabajador.add(jblPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 173, -1, -1));

        txtPago1.setBackground(new java.awt.Color(138, 114, 86));
        txtPago1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtPago1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));
        txtPago1.setEnabled(false);
        tabEditarTrabajador.add(txtPago1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 171, 395, -1));

        jblHoras1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblHoras1.setText("Horas Trabajadas");
        tabEditarTrabajador.add(jblHoras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 204, 120, -1));

        txtHoras1.setBackground(new java.awt.Color(138, 114, 86));
        txtHoras1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtHoras1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));
        txtHoras1.setEnabled(false);
        tabEditarTrabajador.add(txtHoras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 202, 395, -1));

        jblPuesto1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jblPuesto1.setText("Puesto");
        tabEditarTrabajador.add(jblPuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 148, 69, -1));

        txtPuesto1.setBackground(new java.awt.Color(138, 114, 86));
        txtPuesto1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtPuesto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 114, 86), 2));
        txtPuesto1.setEnabled(false);
        tabEditarTrabajador.add(txtPuesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 146, 395, -1));

        btnGuadarNE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/buscar.png"))); // NOI18N
        btnGuadarNE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuadarNEMousePressed(evt);
            }
        });
        tabEditarTrabajador.add(btnGuadarNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        btnEliminarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/eliminar.png"))); // NOI18N
        btnEliminarN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarNMousePressed(evt);
            }
        });
        tabEditarTrabajador.add(btnEliminarN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        btnActN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/act.png"))); // NOI18N
        btnActN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActNMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnActNMouseReleased(evt);
            }
        });
        tabEditarTrabajador.add(btnActN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        tabEditarTrabajador.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 200, -1));

        tabTrabajdores.addTab("Editar⠀⠀⠀⠀⠀", tabEditarTrabajador);

        getContentPane().add(tabTrabajdores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 590, 350));

        jPanel1.setBackground(new java.awt.Color(99, 82, 62));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jblTrabajadores.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        jblTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTrabajadores.setText("TRABAJADORES");
        jblTrabajadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/volver.png"))); // NOI18N
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                volverMousePressed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/tabTrabajadores.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarTablaActionPerformed

    private void volverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMousePressed
        // TODO add your handling code here:
        this.setVisible(false);
        Vd.setVisible(true);
    }//GEN-LAST:event_volverMousePressed

    private void btnGuardarNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarNMousePressed
        // TODO add your handling code here:
        Trabajador trbjaux;
        if(txtNombre.getText().equals("") || txtEdad.getText().equals("")|| txtEmail.getText().equals("")||txtPago.getText().equals("")||txtHoras.getText().equals("")|| txtMatricula.getText().equals("")){
          JOptionPane.showMessageDialog(this,"Campos incompletos Por favor rellene todos los campos");  
        }
        else{
        BD.abrir_ConexionTrbj();
        trbjaux=BD.consultar_trabajador(txtMatricula.getText());
        BD.cerrar_ConexionTrbj();
        if(trbjaux==null){
        trbj.setEdad(Integer.parseInt(txtEdad.getText()));
        trbj.setEmail(txtEmail.getText());
        trbj.setHorasT(Double.parseDouble(txtHoras.getText()));
        trbj.setPago(Double.parseDouble(txtPago.getText()));
        trbj.setNombre(txtNombre.getText());
    trbj.setMatricula(txtMatricula.getText());
    
    if(rbtnVendedor.isSelected()){
        trbj.setPuesto(rbtnVendedor.getText());
    }
    if(rbtnAlmacen.isSelected()){
        trbj.setPuesto(rbtnAlmacen.getText());
    }
    if(rbtnVendedor.isSelected()){
        trbj.setPuesto(rbtnVendedor.getText());
    }
    if(rbtnLimpieza.isSelected()){
        trbj.setPuesto(rbtnLimpieza.getText());
    }
    if(rbtnDiseñador.isSelected()){
        trbj.setPuesto(rbtnDiseñador.getText());
    }
    if(rbtnProductor.isSelected()){
        trbj.setPuesto(rbtnProductor.getText());
    }
    if(rbtnOtro.isSelected()){
        trbj.setPuesto(JOptionPane.showInputDialog(null,"Ingrese El Puesto del Trabajador","Ingresar Usuario",JOptionPane.WARNING_MESSAGE,icon,null,"").toString());
    }
    trbj.salario();
    
       
   
    BD.abrir_ConexionTrbj();
    BD.insertar_Trabajador(trbj);
    BD.cerrar_ConexionTrbj();
    limpiar();
   
        }else
            JOptionPane.showMessageDialog(this, "Por favor Utilizar otra Matricula , esta ya esta en Uso");
   
        }
    }//GEN-LAST:event_btnGuardarNMousePressed

    private void btnBuscarNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarNMousePressed
        // TODO add your handling code here:
          BD.abrir_ConexionTrbj();
        if(txtBuscarTabla.getText().isBlank())
            modelotrbj= BD.consultar_trabajador(modelotrbj);
        else
            modelotrbj=BD.consultar_trabajador(txtBuscarTabla.getText(), modelotrbj);
        
        if(modelotrbj.getRowCount()!=0)
            tblT.setModel(modelotrbj);
        else
            JOptionPane.showMessageDialog(this, "Trabajador no se encontro");
        
        BD.cerrar_ConexionTrbj();
    }//GEN-LAST:event_btnBuscarNMousePressed

    private void btnGuadarNEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuadarNEMousePressed
        // TODO add your handling code here:
        BD.abrir_ConexionTrbj();
        trbj=BD.consultar_trabajador(txtBuscar.getText());
        BD.cerrar_ConexionTrbj();
        
        if(trbj!=null){
            txtNombre1.setEnabled(true);
            txtEdad1.setEnabled(true);
            txtEmail1.setEnabled(true);
            txtPuesto1.setEnabled(true);
            txtPago1.setEnabled(true);
            txtHoras1.setEnabled(true);
            
            txtNombre1.setText(trbj.getNombre());
            txtEdad1.setText(String.valueOf(trbj.getEdad()));
            txtEmail1.setText(trbj.getEmail());
            txtPuesto1.setText(trbj.getPuesto());
            txtPago1.setText(String.valueOf(trbj.getPago()));
            txtHoras1.setText(String.valueOf(trbj.getHorasT()));
            
            
            
            
        }else
            JOptionPane.showMessageDialog(this, "Trabajador no encontrado ");
    }//GEN-LAST:event_btnGuadarNEMousePressed

    private void btnEliminarNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarNMousePressed
        // TODO add your handling code here:
         BD.abrir_ConexionTrbj();
        trbj=BD.consultar_trabajador(txtBuscar.getText());
        if(trbj!=null){
            BD.eliminar_trabajador(trbj);
        JOptionPane.showMessageDialog(this, "Trabajador Elminado de la Base de Datos");
        
        }else{
            JOptionPane.showMessageDialog(this, "Trabajador no encontrado en la Base de Datos");
        }
        BD.cerrar_ConexionTrbj(); 
        limpiar();
    }//GEN-LAST:event_btnEliminarNMousePressed

    private void btnActNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActNMousePressed
        // TODO add your handling code here:
         
        trbj.setNombre(txtNombre1.getText());
        trbj.setEdad(Integer.parseInt(txtEdad1.getText()));
        trbj.setEmail(txtEmail1.getText());
        trbj.setHorasT(Double.parseDouble(txtHoras1.getText()));
        trbj.setPago(Double.parseDouble(txtPago1.getText()));
    trbj.setPuesto(txtPuesto1.getText());
    trbj.salario();
    
    BD.abrir_ConexionTrbj();
    BD.actualizar_Trabajador(trbj);
    BD.cerrar_ConexionTrbj();
    
    limpiar();
    }//GEN-LAST:event_btnActNMousePressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnActNMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActNMouseReleased
        // TODO add your handling code here:
         txtNombre1.setEnabled(false);
            txtEdad1.setEnabled(false);
            txtEmail1.setEnabled(false);
            txtPuesto1.setEnabled(false);
            txtPago1.setEnabled(false);
            txtHoras1.setEnabled(false);
            
    }//GEN-LAST:event_btnActNMouseReleased

    private void btnGuardarNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGuardarNKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarNKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnActN;
    private javax.swing.JLabel btnBuscarN;
    private javax.swing.JLabel btnEliminarN;
    private javax.swing.JLabel btnGuadarNE;
    private javax.swing.JLabel btnGuardarN;
    private javax.swing.ButtonGroup btngroupPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel jblEdad;
    private javax.swing.JLabel jblEdad1;
    private javax.swing.JLabel jblEmail;
    private javax.swing.JLabel jblEmail1;
    private javax.swing.JLabel jblHoras;
    private javax.swing.JLabel jblHoras1;
    private javax.swing.JLabel jblMatricula;
    private javax.swing.JLabel jblNombre;
    private javax.swing.JLabel jblNombre1;
    private javax.swing.JLabel jblPago;
    private javax.swing.JLabel jblPago1;
    private javax.swing.JLabel jblPuesto;
    private javax.swing.JLabel jblPuesto1;
    private javax.swing.JLabel jblTrabajadores;
    private javax.swing.JLabel lblBucarTabla;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JRadioButton rbtnAlmacen;
    private javax.swing.JRadioButton rbtnDiseñador;
    private javax.swing.JRadioButton rbtnLimpieza;
    private javax.swing.JRadioButton rbtnOtro;
    private javax.swing.JRadioButton rbtnProductor;
    private javax.swing.JRadioButton rbtnVendedor;
    private javax.swing.JPanel tabEditarTrabajador;
    private javax.swing.JPanel tabIngresarT;
    private javax.swing.JPanel tabTabla;
    private javax.swing.JTabbedPane tabTrabajdores;
    private javax.swing.JTable tblT;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarTabla;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdad1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JTextField txtHoras1;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtPago1;
    private javax.swing.JTextField txtPuesto1;
    private javax.swing.JLabel volver;
    // End of variables declaration//GEN-END:variables
}
