/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front;
import BD.BD;
import Back.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alanm
 */

public class VentanaTienda extends javax.swing.JFrame {
    Camisa camisa =null;
    VentanaDueño Vd=null;
    BD BDcamisas=null;
    DefaultTableModel modelocamisas = new DefaultTableModel();

    /**
     * Creates new form VentanaTienda
     */
    
    public VentanaTienda() {
        initComponents();
    }
    public VentanaTienda(VentanaDueño Vd,Camisa camisa) {
        this.Vd=Vd;
        this.camisa=camisa;
        BDcamisas = new BD();
        modelocamisas=BDcamisas.crear_modelo_camisa(modelocamisas);
      
        initComponents();
    }
    
    public void limpiar(){
        txtATipo.setText("");
        listColor.setSelectedIndex(0);
        CombBoxTalla.setSelectedIndex(-1);
        spnCantidad.setValue(0);
        txtCodigo.setText("");
        txtBuscar.setText("");
        txtTipoE.setText("");
        listColorE.setSelectedIndex(-1);
        listTallaE.setSelectedIndex(-1);
        txtCantidadE.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tabInvetario = new javax.swing.JTabbedPane();
        tabRegistrar = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtATipo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listColor = new javax.swing.JList<>();
        spnCantidad = new javax.swing.JSpinner();
        txtCodigo = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblTalla = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        btnGuardarN = new javax.swing.JLabel();
        CombBoxTalla = new javax.swing.JComboBox<>();
        tabInventario = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblC = new javax.swing.JTable();
        txtBuscarT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarT = new javax.swing.JLabel();
        tabEditar = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        listColorE = new javax.swing.JList<>();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        listTallaE = new javax.swing.JList<>();
        btnAct = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        txtCantidadE = new javax.swing.JTextField();
        lblTipo1 = new javax.swing.JLabel();
        lblColor1 = new javax.swing.JLabel();
        lblTalla1 = new javax.swing.JLabel();
        lblCantidad1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTipoE = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();
        pnlInventario = new javax.swing.JPanel();
        jblTrabajadores = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabInvetario.setBackground(new java.awt.Color(153, 133, 103));
        tabInvetario.setForeground(new java.awt.Color(0, 0, 0));

        tabRegistrar.setBackground(new java.awt.Color(186, 162, 125));
        tabRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setBackground(new java.awt.Color(153, 133, 103));
        jScrollPane3.setForeground(new java.awt.Color(153, 133, 103));

        txtATipo.setBackground(new java.awt.Color(99, 82, 62));
        txtATipo.setColumns(20);
        txtATipo.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtATipo.setRows(5);
        txtATipo.setText("Ingrese el Tipo de Camisa \nEj. Camisa Color Solido ");
        txtATipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));
        txtATipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtATipoFocusLost(evt);
            }
        });
        txtATipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtATipoMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(txtATipo);

        tabRegistrar.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 130));

        listColor.setBackground(new java.awt.Color(99, 82, 62));
        listColor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));
        listColor.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        listColor.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Blanco", "Negro", "Rojo", "Cafe", "Morado", "Azul", "Verde" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listColor);

        tabRegistrar.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, 130));

        spnCantidad.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        spnCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));
        tabRegistrar.add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 90, -1));

        txtCodigo.setBackground(new java.awt.Color(99, 82, 62));
        txtCodigo.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtCodigo.setText("Codigo");
        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFocusLost(evt);
            }
        });
        txtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtCodigoMouseReleased(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        tabRegistrar.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 92, -1));

        lblTipo.setBackground(new java.awt.Color(0, 0, 0));
        lblTipo.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setText("Tipo :");
        tabRegistrar.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, -1));

        lblColor.setBackground(new java.awt.Color(0, 0, 0));
        lblColor.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblColor.setForeground(new java.awt.Color(0, 0, 0));
        lblColor.setText("Color :");
        tabRegistrar.add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 80, -1));

        lblTalla.setBackground(new java.awt.Color(0, 0, 0));
        lblTalla.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblTalla.setForeground(new java.awt.Color(0, 0, 0));
        lblTalla.setText("Talla :");
        tabRegistrar.add(lblTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, -1));

        lblCantidad.setBackground(new java.awt.Color(0, 0, 0));
        lblCantidad.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblCantidad.setForeground(new java.awt.Color(0, 0, 0));
        lblCantidad.setText("Cantidad :");
        tabRegistrar.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 80, -1));

        btnGuardarN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/save.png"))); // NOI18N
        btnGuardarN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarNMousePressed(evt);
            }
        });
        tabRegistrar.add(btnGuardarN, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        CombBoxTalla.setBackground(new java.awt.Color(99, 82, 62));
        CombBoxTalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XS", "S", "M", "L", "XL", "XXL" }));
        tabRegistrar.add(CombBoxTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        tabInvetario.addTab("Registar Inventario", tabRegistrar);

        tabInventario.setBackground(new java.awt.Color(186, 162, 125));

        tblC.setBackground(new java.awt.Color(153, 133, 103));
        tblC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62)));
        tblC.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        tblC.setForeground(new java.awt.Color(99, 82, 62));
        tblC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblC.setGridColor(new java.awt.Color(99, 82, 62));
        tblC.setSelectionBackground(new java.awt.Color(99, 82, 62));
        tblC.setSelectionForeground(new java.awt.Color(99, 82, 62));
        jScrollPane5.setViewportView(tblC);

        txtBuscarT.setBackground(new java.awt.Color(99, 82, 62));
        txtBuscarT.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtBuscarT.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscarT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));

        jLabel2.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buscar Camisa por Codigo");

        btnBuscarT.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        btnBuscarT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/buscar.png"))); // NOI18N
        btnBuscarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarTMousePressed(evt);
            }
        });

        javax.swing.GroupLayout tabInventarioLayout = new javax.swing.GroupLayout(tabInventario);
        tabInventario.setLayout(tabInventarioLayout);
        tabInventarioLayout.setHorizontalGroup(
            tabInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabInventarioLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscarT)
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
        );
        tabInventarioLayout.setVerticalGroup(
            tabInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabInventarioLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tabInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarT)
                    .addGroup(tabInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscarT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        tabInvetario.addTab("Ver Inventario", tabInventario);

        tabEditar.setBackground(new java.awt.Color(186, 162, 125));

        jScrollPane10.setEnabled(false);

        listColorE.setBackground(new java.awt.Color(99, 82, 62));
        listColorE.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        listColorE.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Blanco", "Negro", "Rojo", "Cafe", "Morado", "Azul", "Verde" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listColorE.setEnabled(false);
        jScrollPane10.setViewportView(listColorE);

        txtBuscar.setBackground(new java.awt.Color(186, 162, 125));
        txtBuscar.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(null);

        lblBuscar.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblBuscar.setForeground(new java.awt.Color(0, 0, 0));
        lblBuscar.setText("Buscar Camisa por Codigo");

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/buscar.png"))); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBuscarMousePressed(evt);
            }
        });

        listTallaE.setBackground(new java.awt.Color(99, 82, 62));
        listTallaE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));
        listTallaE.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        listTallaE.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "XS", "S", "M", "L", "XL", "XXL" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listTallaE.setEnabled(false);
        jScrollPane9.setViewportView(listTallaE);

        btnAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/act.png"))); // NOI18N
        btnAct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnActMouseReleased(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/eliminar.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });

        txtCantidadE.setBackground(new java.awt.Color(99, 82, 62));
        txtCantidadE.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtCantidadE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));
        txtCantidadE.setEnabled(false);

        lblTipo1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblTipo1.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo1.setText("Tipo :");

        lblColor1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblColor1.setForeground(new java.awt.Color(0, 0, 0));
        lblColor1.setText("Color :");

        lblTalla1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblTalla1.setForeground(new java.awt.Color(0, 0, 0));
        lblTalla1.setText("Talla :");

        lblCantidad1.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        lblCantidad1.setForeground(new java.awt.Color(0, 0, 0));
        lblCantidad1.setText("Cantidad :");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        txtTipoE.setBackground(new java.awt.Color(99, 82, 62));
        txtTipoE.setColumns(20);
        txtTipoE.setFont(new java.awt.Font("MS UI Gothic", 3, 14)); // NOI18N
        txtTipoE.setRows(5);
        txtTipoE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 82, 62), 2));
        txtTipoE.setEnabled(false);
        jScrollPane1.setViewportView(txtTipoE);

        javax.swing.GroupLayout tabEditarLayout = new javax.swing.GroupLayout(tabEditar);
        tabEditar.setLayout(tabEditarLayout);
        tabEditarLayout.setHorizontalGroup(
            tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEditarLayout.createSequentialGroup()
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabEditarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblTipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabEditarLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTalla1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(tabEditarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(txtBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAct)
                .addContainerGap())
        );
        tabEditarLayout.setVerticalGroup(
            tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEditarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBuscar)))
                .addGap(2, 2, 2)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipo1)
                    .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTalla1)
                        .addComponent(lblColor1)
                        .addComponent(lblCantidad1)))
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabEditarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabEditarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCantidadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(tabEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(btnAct))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabInvetario.addTab("Editar", tabEditar);

        jPanel1.add(tabInvetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 600, 300));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 769, -1, -1));

        pnlInventario.setBackground(new java.awt.Color(99, 82, 62));
        pnlInventario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jblTrabajadores.setFont(new java.awt.Font("MS UI Gothic", 3, 18)); // NOI18N
        jblTrabajadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblTrabajadores.setText("INVENTARIO");
        jblTrabajadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlInventarioLayout = new javax.swing.GroupLayout(pnlInventario);
        pnlInventario.setLayout(pnlInventarioLayout);
        pnlInventarioLayout.setHorizontalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jblTrabajadores, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        pnlInventarioLayout.setVerticalGroup(
            pnlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jblTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnlInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 620, 30));

        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/volver.png"))); // NOI18N
        btnVolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnVolver1MousePressed(evt);
            }
        });
        jPanel1.add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconosProyecto/Inventario22.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 880, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 800, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoMousePressed
        // TODO add your handling code here:
        if(txtCodigo.getText().equals("Codigo"))
        txtCodigo.setText("");
        
        
    }//GEN-LAST:event_txtCodigoMousePressed

    private void txtCodigoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoMouseReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_txtCodigoMouseReleased

    private void btnBuscarTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarTMousePressed
        // TODO add your handling code here:
        BDcamisas.abrir_ConexionCm();
        if(txtBuscarT.getText().isBlank())
            modelocamisas= BDcamisas.consultar_camisas(modelocamisas);
        else
            modelocamisas=BDcamisas.consultar_camisas(Integer.parseInt(txtBuscarT.getText()), modelocamisas);
        
        if(modelocamisas.getRowCount()!=0)
            tblC.setModel(modelocamisas);
        else
            JOptionPane.showMessageDialog(this, "Camisas con ese codigo  no se encontraron");
        
        BDcamisas.cerrar_ConexionCm();
    }//GEN-LAST:event_btnBuscarTMousePressed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusLost
        // TODO add your handling code here:
        if(txtCodigo.getText().equals(""))
        txtCodigo.setText("Codigo");
    }//GEN-LAST:event_txtCodigoFocusLost

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        // TODO add your handling code here:
        BDcamisas.abrir_ConexionCm();
        camisa=BDcamisas.consultar_camisas(txtBuscar.getText());
        if(camisa!=null){
            BDcamisas.eliminar_camisas(camisa);
            JOptionPane.showMessageDialog(this, "Camisas Eliminadas de la Base de Datos");

        }else{
            JOptionPane.showMessageDialog(this, "Codigo de camisas no encontrado en la Base de Datos");
        }
        BDcamisas.cerrar_ConexionCm();
        limpiar();
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnActMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActMouseReleased
        // TODO add your handling code here:
        txtTipoE.setEnabled(false);
        listColorE.setEnabled(false);
        listTallaE.setEnabled(false);
        txtCantidadE.setEnabled(false);
    }//GEN-LAST:event_btnActMouseReleased

    private void btnActMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActMousePressed
        // TODO add your handling code here:

        camisa.setTipo(txtTipoE.getText());
        camisa.setColor(listColorE.getSelectedValue());
        camisa.setTalla(listTallaE.getSelectedValue());
        camisa.setCantidad(txtCantidadE.getText());

        BDcamisas.abrir_ConexionCm();
        BDcamisas.actualizar_camisas(camisa);
        BDcamisas.cerrar_ConexionCm();

        limpiar();
    }//GEN-LAST:event_btnActMousePressed

    private void btnBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMousePressed
        // TODO add your handling code here:
        BDcamisas.abrir_ConexionCm();
        camisa=BDcamisas.consultar_camisas(txtBuscar.getText());
        BDcamisas.cerrar_ConexionCm();

        if(camisa!=null){
            txtTipoE.setEnabled(true);
            listColorE.setEnabled(true);
            listTallaE.setEnabled(true);
            txtCantidadE.setEnabled(true);

            txtTipoE.setText(camisa.getTipo());
            switch(camisa.getColor()){
                case "Blanco" :
                listColorE.setSelectedIndex(0);
                break;
                case "Negro" :
                listColorE.setSelectedIndex(1);
                break;
                case "Rojo" :
                listColorE.setSelectedIndex(2);
                break;
                case "Cafe" :
                listColorE.setSelectedIndex(3);
                break;
                case "Morado" :
                listColorE.setSelectedIndex(4);
                break;
                case "Azul" :
                listColorE.setSelectedIndex(5);
                break;
                case "Verde" :
                listColorE.setSelectedIndex(6);
                break;

            }
            switch(camisa.getTalla()){
                case "XS" :
                listTallaE.setSelectedIndex(0);
                break;
                case "S" :
                listTallaE.setSelectedIndex(1);
                break;
                case "M" :
                listTallaE.setSelectedIndex(2);
                break;
                case "L" :
                listTallaE.setSelectedIndex(3);
                break;
                case "XL" :
                listTallaE.setSelectedIndex(4);
                break;
                case "XXL" :
                listTallaE.setSelectedIndex(5);
                break;
            }
            txtCantidadE.setText(camisa.getCantidad());

        }else
        JOptionPane.showMessageDialog(this, "Codigo de camisas no encontrado en el Inventario ");

    }//GEN-LAST:event_btnBuscarMousePressed

    private void btnVolver1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver1MousePressed
        // TODO add your handling code here:
         this.setVisible(false);
        Vd.setVisible(true);
    }//GEN-LAST:event_btnVolver1MousePressed

    private void btnGuardarNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarNMousePressed
        // TODO add your handling code here:
        Camisa caux;
            if(listColor.getSelectedValue()==null||CombBoxTalla.getSelectedItem()==null||spnCantidad.getValue()==null){
                JOptionPane.showMessageDialog(this,"Campos incompletos Por favor rellene todos los campos ");
            }else{
                BDcamisas.abrir_ConexionCm();
                caux=BDcamisas.consultar_camisas(txtCodigo.getText());
                BDcamisas.cerrar_ConexionCm();
                if(caux==null){
                camisa.setCantidad(spnCantidad.getValue().toString());
                camisa.setColor(listColor.getSelectedValue());
                camisa.setTalla(CombBoxTalla.getSelectedItem().toString());
                camisa.setTipo(txtATipo.getText());
                camisa.setCodigo(Integer.parseInt(txtCodigo.getText()));
                
                BDcamisas.abrir_ConexionCm();
                BDcamisas.insertar_camisas(camisa);
                BDcamisas.cerrar_ConexionCm();
                limpiar();
                }
                else
                    JOptionPane.showMessageDialog(this, "Por favor Utilizar otro Codigo , este ya esta en Uso");
            }
            
        
        
    }//GEN-LAST:event_btnGuardarNMousePressed

    private void txtATipoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtATipoMousePressed
        // TODO add your handling code here:
        if(txtATipo.getText().equals("Ingrese el Tipo de Camisa \n" +
"Ej. Camisa Color Solido "))
            txtATipo.setText("");
    }//GEN-LAST:event_txtATipoMousePressed

    private void txtATipoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtATipoFocusLost
        // TODO add your handling code here:
        if(txtATipo.getText().equals(""))
            txtATipo.setText("Ingrese el Tipo de Camisa \n" +
"Ej. Camisa Color Solido ");
    }//GEN-LAST:event_txtATipoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CombBoxTalla;
    private javax.swing.JLabel btnAct;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnBuscarT;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnGuardarN;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel btnVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jblTrabajadores;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTalla;
    private javax.swing.JLabel lblTalla1;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JList<String> listColor;
    private javax.swing.JList<String> listColorE;
    private javax.swing.JList<String> listTallaE;
    private javax.swing.JPanel pnlInventario;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JPanel tabEditar;
    private javax.swing.JPanel tabInventario;
    private javax.swing.JTabbedPane tabInvetario;
    private javax.swing.JPanel tabRegistrar;
    private javax.swing.JTable tblC;
    private javax.swing.JTextArea txtATipo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarT;
    private javax.swing.JTextField txtCantidadE;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtTipoE;
    // End of variables declaration//GEN-END:variables
}
